# Config overrides for experiments
DataRoot: /home/user/geoaudio/aporee
DataThreads: 12
Epochs: 300
BatchSize: 256

LossFunction: SymmetricCL
ImageEncoder: ResNet18
SoundReducer: RandomAudioSample
MaxSamples: 1
